#!/usr/bin/env python3
"""Generate a .env file for tusShare with secure random values.

Usage:
    python generate-env.py                  # interactive, writes .env
    python generate-env.py --domain files.example.com
    python generate-env.py --force          # overwrite existing .env
    python generate-env.py --dev            # localhost defaults, skip domain prompt
"""

import argparse
import base64
import os
import secrets
import sys
from pathlib import Path


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def rand_hex(n_bytes: int = 32) -> str:
    return secrets.token_hex(n_bytes)


def rand_b64url(n_bytes: int = 32) -> str:
    return base64.urlsafe_b64encode(secrets.token_bytes(n_bytes)).decode()


def rand_password(length: int = 32) -> str:
    alphabet = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
    return "".join(secrets.choice(alphabet) for _ in range(length))


def prompt(question: str, default: str = "") -> str:
    suffix = f" [{default}]" if default else ""
    try:
        answer = input(f"{question}{suffix}: ").strip()
    except (KeyboardInterrupt, EOFError):
        print()
        sys.exit(0)
    return answer or default


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(description="Generate a tusShare .env file.")
    parser.add_argument("--domain", help="WebAuthn relying-party domain (e.g. files.example.com)")
    parser.add_argument("--force", action="store_true", help="Overwrite an existing .env")
    parser.add_argument("--dev", action="store_true", help="Dev mode: use localhost, skip prompt")
    args = parser.parse_args()

    env_path = Path(".env")

    if env_path.exists() and not args.force:
        print(f"ERROR: {env_path} already exists. Use --force to overwrite.", file=sys.stderr)
        sys.exit(1)

    # --- Domain ---
    if args.dev:
        domain = "localhost"
    elif args.domain:
        domain = args.domain
    else:
        print("tusShare setup — generating .env with secure random values.\n")
        domain = prompt(
            "WebAuthn domain (the exact hostname users will visit — passkeys won't work if this is wrong)"
        )
        if not domain:
            print("ERROR: domain is required. Use --dev for localhost.", file=sys.stderr)
            sys.exit(1)
        domain = domain.rstrip("/").removeprefix("https://").removeprefix("http://")

    # --- Generate secrets ---
    jwt_secret          = rand_hex(32)           # 64-char hex
    pg_superuser_pass   = rand_password(32)
    pg_app_pass         = rand_password(32)
    mfa_key             = rand_b64url(32)
    idp_key             = rand_b64url(32)
    storage_key         = rand_b64url(32)
    notif_key           = rand_b64url(32)

    # --- Write .env ---
    env_content = f"""\
# tusShare configuration — generated by generate-env.py
# Keep this file secret; never commit it to version control.

# =============================================================================
# REQUIRED
# =============================================================================

TUSSHARE_JWT_SECRET={jwt_secret}

TUSSHARE_PG_SUPERUSER_PASSWORD={pg_superuser_pass}
TUSSHARE_PG_PASSWORD={pg_app_pass}

TUSSHARE_DATABASE_URL=postgresql://tusshare:{pg_app_pass}@postgres:5432/tusshare
TUSSHARE_SUPERUSER_URL=postgresql://postgres:{pg_superuser_pass}@postgres:5432/tusshare

# The exact hostname users visit in their browser.
# Passkey registration and login will fail if this does not match.
TUSSHARE_WEBAUTHN_RP_ID={domain}


# =============================================================================
# ENCRYPTION KEYS
# =============================================================================
# Generated explicitly for independent rotation without invalidating sessions.

TUSSHARE_MFA_ENCRYPTION_KEY={mfa_key}
TUSSHARE_IDP_ENCRYPTION_KEY={idp_key}
TUSSHARE_STORAGE_ENCRYPTION_KEY={storage_key}
TUSSHARE_NOTIF_ENCRYPTION_KEY={notif_key}


# =============================================================================
# OPTIONAL — uncomment and configure as needed
# =============================================================================

# Redis — required for multi-worker / multi-container deployments.
# TUSSHARE_REDIS_URL=redis://redis:6379/0

# HTTPS enforcement — enable when behind nginx / Cloudflare TLS termination.
# TUSSHARE_FORCE_HTTPS=false

# Cloudflare proxy — enable only when origin is locked to Cloudflare IPs.
# TUSSHARE_CLOUDFLARE_PROXY_ENABLED=false

# Server-side AV scanning escrow key (ECDH P-256, DER base64).
# Generate with:
#   openssl ecparam -name prime256v1 -genkey -noout \\
#     | openssl pkcs8 -topk8 -nocrypt -outform DER | base64
# TUSSHARE_ESCROW_PRIVATE_KEY=

# Structured JSON logging for log shippers (Filebeat, Vector, Fluentd).
# TUSSHARE_LOG_JSON=false

# Swagger UI — disable in production.
# TUSSHARE_DEBUG=false
"""

    env_path.write_text(env_content, encoding="utf-8")

    print(f"""
.env written to {env_path.resolve()}

  Domain:              {domain}
  JWT secret:          {jwt_secret[:16]}... (64-char hex)
  PG superuser pass:   {pg_superuser_pass[:6]}... (32-char random)
  PG app pass:         {pg_app_pass[:6]}... (32-char random)
  Encryption keys:     MFA / IDP / STORAGE / NOTIF — all generated

Next steps:
  1. Review .env and confirm TUSSHARE_WEBAUTHN_RP_ID matches your domain exactly.
  2. docker compose up -d
  3. On first startup the app will bootstrap the database schema automatically.
  4. Open https://{domain} and create your admin account.

For AV scanning support, see the TUSSHARE_ESCROW_PRIVATE_KEY comment in .env.
""")


if __name__ == "__main__":
    main()
