sonar.exclusions=\
  tusshare-opaque/pyproject.toml,\
  tusshare-opaque/src/**,\
  **/*.lock,\
  **/package-lock.json,\
  **/*.md,\
  **/*.txt,\
  LICENSE,\
  frontend/js/lib/opaque.js,\
  backend/app/sql/setup/schema.sql,\
  tests/**
